pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
            args '-u root'
        }
    }

    environment {
        SONARQUBE_ENV = 'sonarqube'
    }
        RABBITMQ_URL = 'amqp://admin:securepass@rabbitmq:5672'
        TWILIO_ACCOUNT_SID=credentials('TWILIO_ACCOUNT_SID')
        TWILIO_AUTH_TOKEN=credentials('TWILIO_AUTH_TOKEN')
        TWILIO_PHONE_NUMBER= credentials('TWILIO_PHONE_NUMBER')
    }

    stages {
        stage('🔍 Checkout') {
            steps {
                checkout scm
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'ls -la'
                dir('sms') {
                    sh 'python3 --version'
                    sh 'python3 --version'
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('sms/tests/unit') {
                    sh 'python -m pytest test_consumer.py -v --junitxml=test-results.xml || true'
                }
            }
        }

        stage('Integration Tests') {
            steps {
                script {
                    // Esperar a que RabbitMQ esté disponible
                    sh '''
                        cd sms/tests/unit
                        # Enviar mensaje de prueba al bus
                        python test_sms.py "+573001234567" "Mensaje de integración desde Jenkins" || true
                    '''
                }
            }
        }

        stage('Coverage Report') {
            steps {
                sh '''
                    cd sms/tests/unit
                    python -m pytest test_consumer.py --cov=consumer --cov-report=xml --cov-report=html || true
                '''
            }
            
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv("${SONARQUBE_ENV}") {
                        def scannerHome = tool 'sonarForAuth'
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                                -Dsonar.projectKey=sms-service \
                                -Dsonar.sources=sms \
                                -Dsonar.host.url=$SONAR_HOST_URL \
                                -Dsonar.login=$SONAR_AUTH_TOKEN
                        """
                    }
                }
            }
        }
        // Quality Gate and Docker build/deploy stages removed per request.
    }
}